using MZBase.Domain;
using System;
using System.ComponentModel.DataAnnotations;

namespace ChatBase.Backend.Domain.Chat
{
    public class ChatMessage : Model<int>
    {
        /// <summary>
        /// UserId  of the user who has sent the message. If the message is generated by the system, this field will have the value 'system'
        /// </summary>
        [StringLength(200)]
        public required string FromUserId { get; set; }
        /// <summary>
        /// UserId of the receiver of the message
        /// </summary>
        [StringLength(200)]
        public required string ToUserId { get; set; }
        /// <summary>
        /// Body of the message
        /// </summary>
        [StringLength(2500)]
        public required string Body { get; set; }
        /// <summary>
        /// Any meta-data related to the message
        /// </summary>
        [StringLength(500)]
        public string? MetaData { get; set; }
        /// <summary>
        /// Type of the message
        /// </summary>
        public ChatMessageType Type { get; set; }

        /// <summary>
        /// Send time of the message in UTC
        /// </summary>
        public DateTime SendTime { get; set; }
        /// <summary>
        /// Time in which message was received in UTC
        /// </summary>
        public DateTime? ReceiveTime { get; set; }
        /// <summary>
        /// Time in which message was viewed in UTC
        /// </summary>
        public DateTime? ViewTime { get; set; }

        public int? ReplyTo { get; set; }
        public int? ForwardID { get; set; }
        public string? ForwardDetails { get; set; }
        public bool ForwardedFromGroup { get; set; }
    }
}
